<a href="https://colab.research.google.com/github/yogesh-mandor7/learn_pandas_library/blob/main/pandas_some_important_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SOME IMPORTANT SERIES METHODS

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
subs = pd.read_csv('/content/subs.csv')
subs.head()

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [ ]:
ipl = pd.read_csv('/content/kohli_ipl.csv')
ipl.head()

   match_no  runs
0         1     1
1         2    23
2         3    13
3         4    12
4         5     1

In [ ]:
movies = pd.read_csv("/content/bollywood.csv")
movies.head()

                                  movie              lead
0              Uri: The Surgical Strike     Vicky Kaushal
1                         Battalion 609       Vicky Ahuja
2  The Accidental Prime Minister (film)       Anupam Kher
3                       Why Cheat India     Emraan Hashmi
4                       Evening Shadows  Mona Ambegaonkar

In [ ]:
# astype  ye size ko reduce krne me kaam aata h
import sys
sys.getsizeof(ipl)

3604

In [ ]:
ipl  = ipl.astype('int16')
ipl

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [ ]:
sys.getsizeof(ipl)

1024

In [ ]:
# clip
subs.clip(100,200)

     Subscribers gained
0                   100
1                   100
2                   100
3                   100
4                   100
..                  ...
360                 200
361                 200
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [ ]:
# drop duplicate

temp = pd.Series([1,1,2,4,2,5,2,1,6,7,8,])
temp

0     1
1     1
2     2
3     4
4     2
5     5
6     2
7     1
8     6
9     7
10    8
dtype: int64

In [ ]:
temp.drop_duplicates()

0     1
2     2
3     4
5     5
8     6
9     7
10    8
dtype: int64

In [ ]:
subs.duplicated().sum()

np.int64(185)

In [ ]:
temp = pd.Series([1 , 2 , np.nan , 3 , 4 ,np.nan , np.nan ,5 ,6, 7,np.nan ,8,9,10])
temp

0      1.0
1      2.0
2      NaN
3      3.0
4      4.0
5      NaN
6      NaN
7      5.0
8      6.0
9      7.0
10     NaN
11     8.0
12     9.0
13    10.0
dtype: float64

In [ ]:
temp.size

14

In [ ]:
temp.count()

np.int64(10)

In [ ]:
# isnull isse aap kitni null value he pta krr skte he big dataset me
# movies.isnull().sum()
temp.isnull().sum()

np.int64(4)

In [ ]:
# dropna  --> ye function missing value ho hta dega perament
temp.dropna()

0      1.0
1      2.0
3      3.0
4      4.0
7      5.0
8      6.0
9      7.0
11     8.0
12     9.0
13    10.0
dtype: float64

In [ ]:
# fillna  ---> ye missing value ko fill krne me kaam aata h
# temp.fillna(0)
temp.fillna(temp.mean())

0      1.0
1      2.0
2      5.5
3      3.0
4      4.0
5      5.5
6      5.5
7      5.0
8      6.0
9      7.0
10     5.5
11     8.0
12     9.0
13    10.0
dtype: float64

In [ ]:
import pandas as pd
# isin  ==> multiple work krta h

# Re-load ipl to ensure it's a DataFrame, as it was detected as a list.
# This resolves the AttributeError by ensuring ipl is a Pandas object.
ipl = pd.read_csv('/content/kohli_ipl.csv')

# Filter rows where the 'runs' column contains values 23 or 13.
ipl[ipl['runs'].isin([23, 13])]

     match_no  runs
1           2    23
2           3    13
32         33    13
38         39    23
99        100    13
158       159    23
165       166    13
166       167    23

In [ ]:
# apply  ==> custome data ke liye use kiya jata
movies

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [ ]:
movies.apply([lambda x : x.split()[0].upper()])

          movie     lead
       <lambda> <lambda>
0          URI:    VICKY
1     BATTALION    VICKY
2           THE   ANUPAM
3           WHY   EMRAAN
4       EVENING     MONA
...         ...      ...
1495        HUM     SHAH
1496    AANKHEN  AMITABH
1497   SAATHIYA    VIVEK
1498    COMPANY     AJAY
1499      AWARA   AKSHAY

[1500 rows x 2 columns]

In [ ]:
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [ ]:
subs.mean()

Subscribers gained    135.643836
dtype: float64

In [ ]:
# Access the column as a Series to use .apply() on individual values
subs['Subscribers gained'].apply(lambda x : 'good day' if x > subs['Subscribers gained'].mean() else 'bad day')

0       bad day
1       bad day
2       bad day
3       bad day
4       bad day
         ...
360    good day
361    good day
362    good day
363    good day
364    good day
Name: Subscribers gained, Length: 365, dtype: object

In [ ]:
# copy  ==> main data me bina changes kiye copy data prr work

ipl

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [ ]:
new = ipl.head()

In [ ]:
new

   match_no  runs    0
0         1     1  100
1         2    23  100
2         3    13  100
3         4    12  100
4         5     1  100

In [ ]:
ipl.drop(0)

     match_no  runs
1           2    23
2           3    13
3           4    12
4           5     1
5           6     9
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[214 rows x 2 columns]

In [ ]:
ipl.head()

   match_no  runs
0         1     1
1         2    23
2         3    13
3         4    12
4         5     1

In [ ]:
ipl['ym'] = 'ym'
ipl

     match_no  runs   1  ym
0           1     1  ym  ym
1           2    23  ym  ym
2           3    13  ym  ym
3           4    12  ym  ym
4           5     1  ym  ym
..        ...   ...  ..  ..
210       211     0  ym  ym
211       212    20  ym  ym
212       213    73  ym  ym
213       214    25  ym  ym
214       215     7  ym  ym

[215 rows x 4 columns]

In [ ]:
ipl.drop('ym' ,axis=1 )

     match_no  runs   1
0           1     1  ym
1           2    23  ym
2           3    13  ym
3           4    12  ym
4           5     1  ym
..        ...   ...  ..
210       211     0  ym
211       212    20  ym
212       213    73  ym
213       214    25  ym
214       215     7  ym

[215 rows x 3 columns]