<a href="https://colab.research.google.com/github/yogesh-mandor7/learn_pandas_library/blob/main/pandas_groupby_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
movies = pd.read_csv('/content/imdb-top-1000.csv')
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [ ]:
movies.info()
movies.shape
movies.size

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Runtime        1000 non-null   int64
 3   Genre          1000 non-null   object
 4   IMDB_Rating    1000 non-null   float64
 5   Director       1000 non-null   object
 6   Star1          1000 non-null   object
 7   No_of_Votes    1000 non-null   int64
 8   Gross          1000 non-null   float64
 9   Metascore      843 non-null    float64
dtypes: float64(3), int64(2), object(5)
memory usage: 78.3+ KB

10000

In [ ]:
movies.head(2)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0

In [ ]:
# groupby  ==> groupby hmesa category value prr aply hota h like drma movies etc..
genres = movies.groupby('Genre')

In [ ]:
genres

In [ ]:


# Applying builtin aggregation functions on groupby objects
# genres.min()
genres.mean(numeric_only=True)

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333
Biography  136.022727     7.938636  272805.045455  9.404952e+07  76.240506
Comedy     112.129032     7.901290  178195.658065  1.010572e+08  78.720000
Crime      126.392523     8.016822  313398.271028  7.899656e+07  77.080460
Drama      124.737024     7.957439  212343.612457  1.225259e+08  79.701245
Family     107.500000     7.800000  275610.500000  2.195553e+08  79.000000
Fantasy     85.000000     8.000000   73111.000000  3.913633e+08        NaN
Film-Noir  104.000000     7.966667  122405.000000  4.197018e+07  95.666667
Horror     102.090909     7.909091  340232.363636  9.405902e+07  80.000000
Mystery    119.083333     7.975000  350250.333333  1.047014e+08  79.125000
Thriller   108.000000     7.800000   27733.000000  1.755074e+07  81.000000
Western    148.250000     8.350000  322416.250000  1.455538e+07  78.250000

In [ ]:
 # find the top 3 genres by total earning
movies.groupby('Genre').sum()['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [ ]:
movies.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)  # this are much better for 1st code

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [ ]:
movies.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [ ]:
# find the genre with highest avg IMDB rating
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [ ]:
# find director with most popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [ ]:
# find the highest rated movie of each genre
movies.groupby(['Series_Title' , 'Genre'])['IMDB_Rating'].max().sort_values(ascending=False).head(1)

Series_Title              Genre
The Shawshank Redemption  Drama    9.3
Name: IMDB_Rating, dtype: float64

In [ ]:
movies.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [ ]:
# find number of movies done by each actor
# movies['Star1'].value_counts()
movies.groupby('Star1')['Runtime'].count().sort_values(ascending=False)

Star1
Tom Hanks            12
Robert De Niro       11
Clint Eastwood       10
Al Pacino            10
Leonardo DiCaprio     9
                     ..
Gérard Jugnot         1
Günes Sensoy          1
Haluk Bilginer        1
Harriet Andersson     1
Graham Chapman        1
Name: Runtime, Length: 660, dtype: int64

In [ ]:
# GroupBy Attributes and Methods
# find total number of groups -> len
# find items in each group -> size
# first()/last() -> nth item
# get_group -> vs filtering
# groups
# describe
# sample
# nunique

In [ ]:
len(movies.groupby('Genre'))

14

In [ ]:
movies['Genre'].nunique()

14

In [ ]:
movies.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [ ]:
movies['Genre'].value_counts()

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

In [ ]:
genres = movies.groupby('Genre')
# genres.first()
# genres.last()
genres.nth(150)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
483,Amour,2012,127,Drama,7.9,Michael Haneke,Jean-Louis Trintignant,93090,6739492.0,94.0
893,Sicario,2015,121,Action,7.6,Denis Villeneuve,Emily Blunt,371291,46889293.0,82.0
977,The Naked Gun: From the Files of Police Squad!,1988,85,Comedy,7.6,David Zucker,Leslie Nielsen,152871,78756177.0,76.0

In [ ]:
# genres.get_group("Horror")
# genres.get_group("Drama")
genres.get_group("Fantasy")

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN

In [ ]:
genres.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [ ]:
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [ ]:
genres.sample()  # sample random ke liye work krta h

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
623,Avatar,2009,162,Action,7.8,James Cameron,Sam Worthington,1118998,760507625.0,83.0
300,Ben-Hur,1959,212,Adventure,8.1,William Wyler,Charlton Heston,219466,74700000.0,90.0
197,Koe no katachi,2016,130,Animation,8.1,Naoko Yamada,Miyu Irino,47708,37039721.0,78.0
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
565,A Night at the Opera,1935,96,Comedy,7.9,Sam Wood,Edmund Goulding,30580,2537520.0,NaN
125,M - Eine Stadt sucht einen Mörder,1931,117,Crime,8.3,Fritz Lang,Peter Lorre,143434,28877.0,NaN
448,In a Lonely Place,1950,94,Drama,8.0,Nicholas Ray,Humphrey Bogart,26784,532877349.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [ ]:
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [ ]:
# agg method
# passing dict
genres.agg(
    {
        'Runtime' : 'mean',
        'IMDB_Rating' : 'sum',
        'No_of_Votes' : 'mean',
        'Gross' : 'max',
        'Metascore' : 'min'



    }
)

              Runtime  IMDB_Rating    No_of_Votes        Gross  Metascore
Genre
Action     129.046512       1367.3  420246.581395  936662225.0       33.0
Adventure  134.111111        571.5  313557.819444  874211619.0       41.0
Animation   99.585366        650.3  268032.073171  873839108.0       61.0
Biography  136.022727        698.6  272805.045455  753585104.0       48.0
Comedy     112.129032       1224.7  178195.658065  886752933.0       45.0
Crime      126.392523        857.8  313398.271028  790482117.0       47.0
Drama      124.737024       2299.7  212343.612457  924558264.0       28.0
Family     107.500000         15.6  275610.500000  435110554.0       67.0
Fantasy     85.000000         16.0   73111.000000  445151978.0        NaN
Film-Noir  104.000000         23.9  122405.000000  123353292.0       94.0
Horror     102.090909         87.0  340232.363636  298791505.0       46.0
Mystery    119.083333         95.7  350250.333333  474203697.0       52.0
Thriller   108.000000          7.8   27733.000000   17550741.0       81.0
Western    148.250000         33.4  322416.250000   31800000.0       69.0

In [ ]:
movies.head(2)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0

In [ ]:
# passing list
genres[['Runtime', 'IMDB_Rating', 'No_of_Votes', 'Gross', 'Metascore']].agg(['min','max','mean', 'sum'])

          Runtime                         IMDB_Rating                         \
              min  max        mean    sum         min  max      mean     sum
Genre
Action         45  321  129.046512  22196         7.6  9.0  7.949419  1367.3
Adventure      88  228  134.111111   9656         7.6  8.6  7.937500   571.5
Animation      71  137   99.585366   8166         7.6  8.6  7.930488   650.3
Biography      93  209  136.022727  11970         7.6  8.9  7.938636   698.6
Comedy         68  188  112.129032  17380         7.6  8.6  7.901290  1224.7
Crime          80  229  126.392523  13524         7.6  9.2  8.016822   857.8
Drama          64  242  124.737024  36049         7.6  9.3  7.957439  2299.7
Family        100  115  107.500000    215         7.8  7.8  7.800000    15.6
Fantasy        76   94   85.000000    170         7.9  8.1  8.000000    16.0
Film-Noir     100  108  104.000000    312         7.8  8.1  7.966667    23.9
Horror         71  122  102.090909   1123         7.6  8.5  7.909091    87.0
Mystery        96  138  119.083333   1429         7.6  8.4  7.975000    95.7
Thriller      108  108  108.000000    108         7.8  7.8  7.800000     7.8
Western       132  165  148.250000    593         7.8  8.8  8.350000    33.4

          No_of_Votes                                          Gross  \
                  min      max           mean       sum          min
Genre
Action          25312  2303232  420246.581395  72282412       3296.0
Adventure       29999  1512360  313557.819444  22576163      61001.0
Animation       25229   999790  268032.073171  21978630     128985.0
Biography       27254  1213505  272805.045455  24006844      21877.0
Comedy          26337   939631  178195.658065  27620327       1305.0
Crime           27712  1826188  313398.271028  33533615       6013.0
Drama           25088  2343110  212343.612457  61367304       3600.0
Family         178731   372490  275610.500000    551221    4000000.0
Fantasy         57428    88794   73111.000000    146222  337574718.0
Film-Noir       59556   158731  122405.000000    367215     449191.0
Horror          27007   787806  340232.363636   3742556      89029.0
Mystery         33982  1129894  350250.333333   4203004    1035953.0
Thriller        27733    27733   27733.000000     27733   17550741.0
Western         65659   688390  322416.250000   1289665    5321508.0

                                                   Metascore         \
                   max          mean           sum       min    max
Genre
Action     936662225.0  1.897224e+08  3.263226e+10      33.0   98.0
Adventure  874211619.0  1.319017e+08  9.496922e+09      41.0  100.0
Animation  873839108.0  1.784326e+08  1.463147e+10      61.0   96.0
Biography  753585104.0  9.404952e+07  8.276358e+09      48.0   97.0
Comedy     886752933.0  1.010572e+08  1.566387e+10      45.0   99.0
Crime      790482117.0  7.899656e+07  8.452632e+09      47.0  100.0
Drama      924558264.0  1.225259e+08  3.540997e+10      28.0  100.0
Family     435110554.0  2.195553e+08  4.391106e+08      67.0   91.0
Fantasy    445151978.0  3.913633e+08  7.827267e+08       NaN    NaN
Film-Noir  123353292.0  4.197018e+07  1.259105e+08      94.0   97.0
Horror     298791505.0  9.405902e+07  1.034649e+09      46.0   97.0
Mystery    474203697.0  1.047014e+08  1.256417e+09      52.0  100.0
Thriller    17550741.0  1.755074e+07  1.755074e+07      81.0   81.0
Western     31800000.0  1.455538e+07  5.822151e+07      69.0   90.0


                mean      sum
Genre
Action     73.419580  10499.0
Adventure  78.437500   5020.0
Animation  81.093333   6082.0
Biography  76.240506   6023.0
Comedy     78.720000   9840.0
Crime      77.080460   6706.0
Drama      79.701245  19208.0
Family     79.000000    158.0
Fantasy          NaN      0.0
Film-Noir  95.666667    287.0
Horror     80.000000    880.0
Mystery    79.125000    633.0
Thriller   81.000000     81.0
Western    78.250000    313.0

In [ ]:
genres.agg(
    {
        'Runtime' : ['min','mean'],
        'IMDB_Rating' : 'sum',
        'No_of_Votes' : ['sum', 'mean'],
        'Gross' : 'max',
        'Metascore' : 'min'



    }
)

          Runtime             IMDB_Rating No_of_Votes                 \
              min        mean         sum         sum           mean
Genre
Action         45  129.046512      1367.3    72282412  420246.581395
Adventure      88  134.111111       571.5    22576163  313557.819444
Animation      71   99.585366       650.3    21978630  268032.073171
Biography      93  136.022727       698.6    24006844  272805.045455
Comedy         68  112.129032      1224.7    27620327  178195.658065
Crime          80  126.392523       857.8    33533615  313398.271028
Drama          64  124.737024      2299.7    61367304  212343.612457
Family        100  107.500000        15.6      551221  275610.500000
Fantasy        76   85.000000        16.0      146222   73111.000000
Film-Noir     100  104.000000        23.9      367215  122405.000000
Horror         71  102.090909        87.0     3742556  340232.363636
Mystery        96  119.083333        95.7     4203004  350250.333333
Thriller      108  108.000000         7.8       27733   27733.000000
Western       132  148.250000        33.4     1289665  322416.250000

                 Gross Metascore
                   max       min
Genre
Action     936662225.0      33.0
Adventure  874211619.0      41.0
Animation  873839108.0      61.0
Biography  753585104.0      48.0
Comedy     886752933.0      45.0
Crime      790482117.0      47.0
Drama      924558264.0      28.0
Family     435110554.0      67.0
Fantasy    445151978.0       NaN
Film-Noir  123353292.0      94.0
Horror     298791505.0      46.0
Mystery    474203697.0      52.0
Thriller    17550741.0      81.0
Western     31800000.0      69.0

In [ ]:
# split (apply) combine
# apply ==> builtin function
genres.apply(min)

/tmp/ipykernel_826/2412683365.py:3: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  genres.apply(min)
/tmp/ipykernel_826/2412683365.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(min)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300,1924,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,NaN
Adventure,2001: A Space Odyssey,1925,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,NaN
Animation,Akira,1940,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,NaN
Biography,12 Years a Slave,1928,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,NaN
Comedy,(500) Days of Summer,1921,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,NaN
Crime,12 Angry Men,1931,80,Crime,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,NaN
Drama,1917,1925,64,Drama,7.6,Aamir Khan,Abhay Deol,25088,3600.0,NaN
Family,E.T. the Extra-Terrestrial,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,Fantasy,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,Film-Noir,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,Horror,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,Mystery,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,NaN
Thriller,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,Western,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [ ]:
# find number of movies  starting with A for each group
def func(group):
  return group['Series_Title'].str.startswith('A').sum()

In [ ]:
genres.apply(func)

/tmp/ipykernel_826/127917597.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(func)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [ ]:
# find ranking of each movie in the group according to IMDB Score
def rank_movie(group):
  group['genre_ranking'] = group['IMDB_Rating'].rank(ascending = False)
  return group

In [ ]:
genres.apply(rank_movie)

/tmp/ipykernel_826/2409710219.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(rank_movie)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              genre_ranking
Genre
Action   2              1.0
         5              2.0
         8              3.5
         10             3.5
         13             6.0
...                     ...
Thriller 700            1.0
Western  12             1.0
         48             2.0
         115            3.0
         691            4.0

[1000 rows x 11 columns]

In [ ]:
def normal(group):
    min_rating = group['IMDB_Rating'].min()
    max_rating = group['IMDB_Rating'].max()
    # Use an if-else structure to correctly handle cases where max_rating - min_rating is zero
    if (max_rating - min_rating) == 0:
        group['normalized_rating'] = 0.0
    else:
        group['normalized_rating'] = (group['IMDB_Rating'] - min_rating) / (max_rating - min_rating)
    return group

genres.apply(normal)

/tmp/ipykernel_826/1032447001.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(normal)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              normalized_rating
Genre
Action   2             1.000000
         5             0.928571
         8             0.857143
         10            0.857143
         13            0.785714
...                         ...
Thriller 700           0.000000
Western  12            1.000000
         48            0.700000
         115           0.500000
         691           0.000000

[1000 rows x 11 columns]

In [ ]:
# groupby multiple columns
duo = movies.groupby(['Director' , 'Star1'])
duo

# size
duo.size()

Director             Star1
Aamir Khan           Amole Gupte       1
Aaron Sorkin         Eddie Redmayne    1
Abdellatif Kechiche  Léa Seydoux       1
Abhishek Chaubey     Shahid Kapoor     1
Abhishek Kapoor      Amit Sadh         1
                                      ..
Zaza Urushadze       Lembit Ulfsak     1
Zoya Akhtar          Hrithik Roshan    1
                     Vijay Varma       1
Çagan Irmak          Çetin Tekindor    1
Ömer Faruk Sorak     Cem Yilmaz        1
Length: 898, dtype: int64

In [ ]:
# get_group
duo.get_group(('Aamir Khan' ,'Amole Gupte' ))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN

In [ ]:
# find the most earing movies
duo['Gross'].sum().sort_values(ascending=0).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [ ]:
# find the best (in - terms of metascore(avg)) actor => genre
movies.groupby(['Star1' , 'Genre'])['Metascore'].mean().reset_index().sort_values('Metascore' , ascending=0).head(1)

             Star1      Genre  Metascore
606  Peter O'Toole  Adventure      100.0

In [ ]:
# agg on multiple groupby
duo.agg(['min' , 'sum' , 'max'])

                                                  Series_Title  \
                                                           min
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab
Abhishek Kapoor     Amit Sadh                      Kai po che!
...                                                        ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara
                    Vijay Varma                      Gully Boy
Çagan Irmak         Çetin Tekindor              Babam ve Oglum
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.

                                                                \
                                                           sum
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab
Abhishek Kapoor     Amit Sadh                      Kai po che!
...                                                        ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara
                    Vijay Varma                      Gully Boy
Çagan Irmak         Çetin Tekindor              Babam ve Oglum
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.

                                                               Released_Year  \
                                                           max           min
Director            Star1
Aamir Khan          Amole Gupte               Taare Zameen Par          2007
Aaron Sorkin        Eddie Redmayne  The Trial of the Chicago 7          2020
Abdellatif Kechiche Léa Seydoux                 La vie d'Adèle          2013
Abhishek Chaubey    Shahid Kapoor                  Udta Punjab          2016
Abhishek Kapoor     Amit Sadh                      Kai po che!          2013
...                                                        ...           ...
Zaza Urushadze      Lembit Ulfsak                  Mandariinid          2013
Zoya Akhtar         Hrithik Roshan    Zindagi Na Milegi Dobara          2011
                    Vijay Varma                      Gully Boy          2019
Çagan Irmak         Çetin Tekindor              Babam ve Oglum          2005
Ömer Faruk Sorak    Cem Yilmaz                        G.O.R.A.          2004

                                               Runtime                Genre  \
                                     sum   max     min  sum  max        min
Director            Star1
Aamir Khan          Amole Gupte     2007  2007     165  165  165      Drama
Aaron Sorkin        Eddie Redmayne  2020  2020     129  129  129      Drama
Abdellatif Kechiche Léa Seydoux     2013  2013     180  180  180      Drama
Abhishek Chaubey    Shahid Kapoor   2016  2016     148  148  148     Action
Abhishek Kapoor     Amit Sadh       2013  2013     130  130  130      Drama
...                                  ...   ...     ...  ...  ...        ...
Zaza Urushadze      Lembit Ulfsak   2013  2013      87   87   87      Drama
Zoya Akhtar         Hrithik Roshan  2011  2011     155  155  155     Comedy
                    Vijay Varma     2019  2019     154  154  154      Drama
Çagan Irmak         Çetin Tekindor  2005  2005     112  112  112      Drama
Ömer Faruk Sorak    Cem Yilmaz      2004  2004     127  127  127  Adventure

                                    ... IMDB_Rating No_of_Votes          \
                                    ...         max         min     sum
Director            Star1           ...
Aamir Khan          Amole Gupte     ...         8.4      168895  168895
Aaron Sorkin        Eddie Redmayne  ...         7.8       89896   89896
Abdellatif Kechiche Léa Seydoux     ...         7.7      138741  138741
Abhishek Chaubey    Shahid Kapoor   ...         7.8       27175   27175
Abhishek Kapoor     Amit Sadh       ...         7.7       32628   32628
...                                 ...         ...         ...     ...
Zaza Urushadze      Lembit Ulfsak   ...         8.2       40382   40382
Zoya Akhtar         Hrithik Roshan  ...         8.1       67927   67927
                    Vijay Varma     ...         8.0       31886   31886
Çagan Irmak         Çetin Tekindor  ...         8.3       78925   78925
Ömer Faruk Sorak    Cem Yilmaz      ...         8.0       56960   56960

                                                  Gross               \
                                       max          min          sum
Director            Star1
Aamir Khan          Amole Gupte     168895    1223869.0    1223869.0
Aaron Sorkin        Eddie Redmayne   89896  853090410.0  853090410.0
Abdellatif Kechiche Léa Seydoux     138741    2199675.0    2199675.0
Abhishek Chaubey    Shahid Kapoor    27175  218428303.0  218428303.0
Abhishek Kapoor     Amit Sadh        32628    1122527.0    1122527.0
...                                    ...          ...          ...
Zaza Urushadze      Lembit Ulfsak    40382     144501.0     144501.0
Zoya Akhtar         Hrithik Roshan   67927    3108485.0    3108485.0
                    Vijay Varma      31886    5566534.0    5566534.0
Çagan Irmak         Çetin Tekindor   78925  461855363.0  461855363.0
Ömer Faruk Sorak    Cem Yilmaz       56960  196206077.0  196206077.0

                                                Metascore
                                            max       min   sum   max
Director            Star1
Aamir Khan          Amole Gupte       1223869.0       NaN   0.0   NaN
Aaron Sorkin        Eddie Redmayne  853090410.0      77.0  77.0  77.0
Abdellatif Kechiche Léa Seydoux       2199675.0      89.0  89.0  89.0
Abhishek Chaubey    Shahid Kapoor   218428303.0       NaN   0.0   NaN
Abhishek Kapoor     Amit Sadh         1122527.0      40.0  40.0  40.0
...                                         ...       ...   ...   ...
Zaza Urushadze      Lembit Ulfsak      144501.0      73.0  73.0  73.0
Zoya Akhtar         Hrithik Roshan    3108485.0       NaN   0.0   NaN
                    Vijay Varma       5566534.0      65.0  65.0  65.0
Çagan Irmak         Çetin Tekindor  461855363.0       NaN   0.0   NaN
Ömer Faruk Sorak    Cem Yilmaz      196206077.0       NaN   0.0   NaN

[898 rows x 24 columns]

In [ ]:
ipl = pd.read_csv('/content/deliveries.csv')
ipl.head(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [ ]:
ipl.describe()

,match_id,inning,over,ball,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs
count,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000,179078.000000
mean,1802.252957,1.482952,10.162488,3.615587,0.000452,0.036721,0.004936,0.021136,0.004183,0.000056,1.246864,0.067032,1.313897
std,3472.322805,0.502074,5.677684,1.806966,0.021263,0.251161,0.116480,0.194908,0.070492,0.016709,1.608270,0.342553,1.605422
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,190.000000,1.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,379.000000,1.000000,10.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
75%,567.000000,2.000000,15.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,11415.000000,5.000000,20.000000,9.000000,1.000000,5.000000,4.000000,5.000000,5.000000,5.000000,7.000000,7.000000,10.000000

In [ ]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179078 entries, 0 to 179077
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          179078 non-null  int64
 1   inning            179078 non-null  int64
 2   batting_team      179078 non-null  object
 3   bowling_team      179078 non-null  object
 4   over              179078 non-null  int64
 5   ball              179078 non-null  int64
 6   batsman           179078 non-null  object
 7   non_striker       179078 non-null  object
 8   bowler            179078 non-null  object
 9   is_super_over     179078 non-null  int64
 10  wide_runs         179078 non-null  int64
 11  bye_runs          179078 non-null  int64
 12  legbye_runs       179078 non-null  int64
 13  noball_runs       179078 non-null  int64
 14  penalty_runs      179078 non-null  int64
 15  batsman_runs      179078 non-null  int64
 16  extra_runs        179078 non-null  int64
 17  total_runs        179078 non-null  int64
 18  player_dismissed  8834 non-null    object
 19  dismissal_kind    8834 non-null    object
 20  fielder           6448 non-null    object
dtypes: int64(13), object(8)
memory usage: 28.7+ MB

In [ ]:
ipl.shape

(179078, 21)

In [ ]:
# find the top 10 batsman in terms of runs
ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [ ]:
ipl.head(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [ ]:
# find the batsman with max no of six
six = ipl[ipl['batsman_runs'] == 6]

six.groupby('batsman')['batsman_runs'].count().sort_values(ascending=0)

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
                 ...
AN Ahmed            1
AD Mascarenhas      1
TA Boult            1
T Kohli             1
TS Mills            1
Name: batsman_runs, Length: 336, dtype: int64

In [ ]:
# find batsman with most number of 4's and 6's last 5 over
temp_df = ipl[ipl['over'] > 15]
temp_df = temp_df[(temp_df['batsman_runs'] == 4) | (temp_df['batsman_runs'] == 6)]

# temp_df.value_counts('batsman')
temp_df.groupby('batsman')['batsman_runs'].count().sort_values(ascending=0).head(1).index[0]

'MS Dhoni'

In [ ]:
# find V Kohli's record against all teams
temp_df = ipl[ipl['batsman'] == 'V Kohli']

temp_df.groupby('bowling_team')['batsman_runs'].sum().reset_index()

               bowling_team  batsman_runs
0       Chennai Super Kings           749
1           Deccan Chargers           306
2            Delhi Capitals            66
3          Delhi Daredevils           763
4             Gujarat Lions           283
5           Kings XI Punjab           636
6      Kochi Tuskers Kerala            50
7     Kolkata Knight Riders           675
8            Mumbai Indians           628
9             Pune Warriors           128
10         Rajasthan Royals           370
11   Rising Pune Supergiant            83
12  Rising Pune Supergiants           188
13      Sunrisers Hyderabad           509

In [ ]:
# create a function that can return the highest score of any batsman

temp_df = ipl[ipl['batsman'] == 'V Kohli']

temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=0).head(1).values[0]

np.int64(113)

In [ ]:
def high_score(batsman):
  temp_df = ipl[ipl['batsman'] == batsman]

  return temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=0).head(1).values[0]

In [ ]:
high_score('DA Warner')

np.int64(126)