<a href="https://colab.research.google.com/github/yogesh-mandor7/learn_pandas_library/blob/main/session_3_pandas_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

### Pandas Series

A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

In [108]:
import numpy as np
import pandas as pd

In [109]:
# string
country = ['India','Pakistan','USA','Nepal','Srilanka']

pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4    Srilanka
dtype: object

In [110]:
# integers
runs = [13,24,56,78,100]

runs_ser = pd.Series(runs)

In [111]:
# custom index
marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']

pd.Series(marks,index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [112]:
# setting a name
marks = pd.Series(marks,index=subjects,name='Nitish ke marks')
marks

maths       67
english     57
science     89
hindi      100
Name: Nitish ke marks, dtype: int64

In [113]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}

marks_series = pd.Series(marks,name='yogesh ke marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: yogesh ke marks, dtype: int64

### Series Attributes

In [114]:
# size
marks_series.size

4

In [115]:
# dtype
marks_series.dtype

dtype('int64')

In [116]:
# name
marks_series.name

'yogesh ke marks'

In [117]:
# is_unique
marks_series.is_unique

pd.Series([1,1,2,3,4,5]).is_unique

False

In [118]:
# index
marks_series.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [119]:
runs_ser.index

RangeIndex(start=0, stop=5, step=1)

In [120]:
# values
marks_series.values

array([ 67,  57,  89, 100])

### Series using read_csv

In [121]:
# with one col
subs = pd.read_csv('/content/subs.csv')
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [122]:
# with 2 cols
vk = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no')
vk

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [123]:
movies = pd.read_csv('/content/bollywood.csv',index_col='movie')
movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

### Series methods

In [124]:
# head and tail
subs.head()

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [125]:
vk.head(3)

          runs
match_no
1            1
2           23
3           13

In [126]:
vk.tail(10)

          runs
match_no
206          0
207          0
208          9
209         58
210         30
211          0
212         20
213         73
214         25
215          7

In [127]:
# sample
movies.sample(5)

                                         lead
movie
Bluffmaster!                Abhishek Bachchan
Aakrosh (2010 film)                Ajay Devgn
Darling (2007 Indian film)       Fardeen Khan
Thank You (2011 film)            Akshay Kumar
Khoya Khoya Chand                Shiney Ahuja

In [128]:
# value_counts -> movies
movies.value_counts()

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Naveen Bawa          1
Naushaad Abbas       1
Nauheed Cyrusi       1
Natalia Janoszek     1
Nishikant Kamat      1
Name: count, Length: 566, dtype: int64

In [129]:
vk.sort_values(by='runs', ascending=False).head(1).values[0]

array([113])

In [130]:
vk.sort_values(by='runs', ascending=False)

          runs
match_no
128        113
126        109
123        108
120        100
164        100
...        ...
93           0
130          0
206          0
207          0
211          0

[215 rows x 1 columns]

In [131]:
# sort_index -> inplace -> movies
movies.sort_index(ascending=False,inplace=True)

In [132]:
# count
vk.count()

runs    215
dtype: int64

In [133]:
# sum -> product
subs.sum()

Subscribers gained    49510
dtype: int64

In [134]:
# mean -> median -> mode -> std -> var
subs.mean()
print(vk.median())
print(movies.mode())
print(subs.std())
print(vk.var())

runs    24.0
dtype: float64
           lead
0  Akshay Kumar
Subscribers gained    62.675023
dtype: float64
runs    688.002478
dtype: float64

In [135]:
# min/max
subs.max()

Subscribers gained    396
dtype: int64

In [136]:
# describe
subs.describe()

       Subscribers gained
count          365.000000
mean           135.643836
std             62.675023
min             33.000000
25%             88.000000
50%            123.000000
75%            177.000000
max            396.000000

### Series Indexing

In [137]:
# integer indexing
x = pd.Series([12,13,14,35,46,57,58,79,9])
x

0    12
1    13
2    14
3    35
4    46
5    57
6    58
7    79
8     9
dtype: int64

In [138]:
movies

                                        lead
movie
Zor Lagaa Ke...Haiya!          Meghan Jadhav
Zokkomon                     Darsheel Safary
Zindagi Tere Naam         Mithun Chakraborty
Zindagi Na Milegi Dobara      Hrithik Roshan
Zindagi 50-50                    Veena Malik
...                                      ...
2 States (2014 film)            Arjun Kapoor
1971 (2007 film)              Manoj Bajpayee
1920: The Evil Returns           Vicky Ahuja
1920: London                   Sharman Joshi
1920 (film)                 Rajniesh Duggall

[1500 rows x 1 columns]

In [139]:
# negative indexing
# Use .iloc for positional indexing when the index labels are integers
x.iloc[-1]

np.int64(9)

In [140]:
# slicing
vk[5:16]

          runs
match_no
6            9
7           34
8            0
9           21
10           3
11          10
12          38
13           3
14          11
15          50
16           2

In [141]:
# negative slicing
vk[-5:]

          runs
match_no
211          0
212         20
213         73
214         25
215          7

In [142]:
movies[::2]

                                     lead
movie
Zor Lagaa Ke...Haiya!       Meghan Jadhav
Zindagi Tere Naam      Mithun Chakraborty
Zindagi 50-50                 Veena Malik
Zinda (film)                  Sanjay Dutt
Zid (2014 film)            Mannara Chopra
...                                   ...
3 Storeys                     Aisha Ahmed
3 Deewarein              Naseeruddin Shah
22 Yards                      Barun Sobti
1971 (2007 film)           Manoj Bajpayee
1920: London                Sharman Joshi

[750 rows x 1 columns]

In [143]:
# fancy indexing
# Use .iloc to access rows by position in a DataFrame
vk.iloc[[1,3,4,5]]

          runs
match_no
2           23
4           12
5            1
6            9

### Editing Series

In [144]:
# using indexing
marks_series[1] = 100
marks_series

/tmp/ipykernel_4907/3621369324.py:2: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  marks_series[1] = 100

maths       67
english    100
science     89
hindi      100
Name: yogesh ke marks, dtype: int64

In [145]:
# what if an index does not exist
marks_series['evs'] = 100

In [146]:
marks_series

maths       67
english    100
science     89
hindi      100
evs        100
Name: yogesh ke marks, dtype: int64

In [147]:
# slicing
runs_ser[2:4] = [100,100]
runs_ser

0     13
1     24
2    100
3    100
4    100
dtype: int64

In [148]:
# fancy indexing
runs_ser[[0,3,4]] = [0,0,0]
runs_ser

0      0
1     24
2    100
3      0
4      0
dtype: int64

In [149]:
# using index label
movies['2 States (2014 film)'] = 'Alia Bhatt'
movies

                                        lead 2 States (2014 film)
movie
Zor Lagaa Ke...Haiya!          Meghan Jadhav           Alia Bhatt
Zokkomon                     Darsheel Safary           Alia Bhatt
Zindagi Tere Naam         Mithun Chakraborty           Alia Bhatt
Zindagi Na Milegi Dobara      Hrithik Roshan           Alia Bhatt
Zindagi 50-50                    Veena Malik           Alia Bhatt
...                                      ...                  ...
2 States (2014 film)            Arjun Kapoor           Alia Bhatt
1971 (2007 film)              Manoj Bajpayee           Alia Bhatt
1920: The Evil Returns           Vicky Ahuja           Alia Bhatt
1920: London                   Sharman Joshi           Alia Bhatt
1920 (film)                 Rajniesh Duggall           Alia Bhatt

[1500 rows x 2 columns]

### Copy and Views

### Series with Python Functionalities

In [150]:
# len/type/dir/sorted/max/min
print(len(subs))
print(type(subs))
print(dir(subs))
print(sorted(subs))
print(min(subs))
print(max(subs))

365
<class 'pandas.core.frame.DataFrame'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__dataframe_consortium_standard__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_arith_method_with_reindex', '_as_manager', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_create_data_for_split_and_tight_to_dict', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item_cache', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_nocopy', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_copy', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_item_cache', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_maybe_cache_changed', '_maybe_update_cacher', '_metadata', '_mgr', '_min_count_stat_function', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_sanitize_column', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'applymap', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'backfill', 'between_time', 'bfill', 'bigquery', 'bool', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_geometry', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_gbq', 'to_hdf', 'to_html', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']
['Subscribers gained']
Subscribers gained
Subscribers gained

In [151]:
# type conversion
list(marks_series)

[67, 100, 89, 100, 100]

In [152]:
dict(marks_series)

{'maths': np.int64(67),
 'english': np.int64(100),
 'science': np.int64(89),
 'hindi': np.int64(100),
 'evs': np.int64(100)}

### Some Important Series Methods

In [153]:
# astype
# between
# clip
# drop_duplicates
# isnull
# dropna
# fillna
# isin
# apply
# copy

In [154]:
# astype
import sys
sys.getsizeof(vk)

3472

In [155]:
sys.getsizeof(vk.astype('int16'))

2182

In [156]:
# between
vk[vk['runs'].between(51, 99)].size

43

In [157]:
# clip
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [158]:
subs.clip(100,200)

     Subscribers gained
0                   100
1                   100
2                   100
3                   100
4                   100
..                  ...
360                 200
361                 200
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [159]:
# drop_duplicates
temp = pd.Series([1,1,2,2,3,3,4,4])
temp

0    1
1    1
2    2
3    2
4    3
5    3
6    4
7    4
dtype: int64

In [160]:
temp.drop_duplicates(keep='last')

1    1
3    2
5    3
7    4
dtype: int64

In [161]:
temp.duplicated().sum()

np.int64(4)

In [162]:
# isnull
temp.isnull().sum()

np.int64(0)

In [163]:
# dropna
temp.dropna()

0    1
1    1
2    2
3    2
4    3
5    3
6    4
7    4
dtype: int64

In [164]:
# fillna
temp.fillna(temp.mean())

0    1
1    1
2    2
3    2
4    3
5    3
6    4
7    4
dtype: int64

In [165]:
# isin
vk[(vk == 49) | (vk == 99)]

          runs
match_no
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
...        ...
211        NaN
212        NaN
213        NaN
214        NaN
215        NaN

[215 rows x 1 columns]

In [166]:
vk[vk.isin([49,99])]

          runs
match_no
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
...        ...
211        NaN
212        NaN
213        NaN
214        NaN
215        NaN

[215 rows x 1 columns]

In [167]:
# apply
movies

                                        lead 2 States (2014 film)
movie
Zor Lagaa Ke...Haiya!          Meghan Jadhav           Alia Bhatt
Zokkomon                     Darsheel Safary           Alia Bhatt
Zindagi Tere Naam         Mithun Chakraborty           Alia Bhatt
Zindagi Na Milegi Dobara      Hrithik Roshan           Alia Bhatt
Zindagi 50-50                    Veena Malik           Alia Bhatt
...                                      ...                  ...
2 States (2014 film)            Arjun Kapoor           Alia Bhatt
1971 (2007 film)              Manoj Bajpayee           Alia Bhatt
1920: The Evil Returns           Vicky Ahuja           Alia Bhatt
1920: London                   Sharman Joshi           Alia Bhatt
1920 (film)                 Rajniesh Duggall           Alia Bhatt

[1500 rows x 2 columns]

In [168]:
# apply
# Select the specific column first, then apply the string operation
movies['lead'].apply(lambda x: x.split()[0].upper())

movie
Zor Lagaa Ke...Haiya!         MEGHAN
Zokkomon                    DARSHEEL
Zindagi Tere Naam             MITHUN
Zindagi Na Milegi Dobara     HRITHIK
Zindagi 50-50                  VEENA
                              ...
2 States (2014 film)           ARJUN
1971 (2007 film)               MANOJ
1920: The Evil Returns         VICKY
1920: London                 SHARMAN
1920 (film)                 RAJNIESH
Name: lead, Length: 1500, dtype: object

In [169]:
# copy
# Creating a copy of the series to avoid modifying the original data
vk_copy = vk.copy()
vk_copy.iloc[0] = 1000

print("Original first value:", vk.iloc[0].values[0])
print("Copy first value:", vk_copy.iloc[0].values[0])

Original first value: 1
Copy first value: 1000